# Generated by Django 3.2.9 on 2021-11-20 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('dia', models.CharField(choices=[('L', 'Lunes'), ('M', 'Martes'), ('N', 'Miércoles'), ('J', 'Jueves'), ('V', 'Viernes')], max_length=1)),
                ('clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_clase', to='mandala_api.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clase', models.ManyToManyField(to='mandala_api.Horario')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_instructor', to='mandala_api.instructor'),
        ),
    ]
