# Generated by Django 3.2.9 on 2021-11-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
