# Generated by Django 3.2.9 on 2021-11-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_api', '0002_instructor_apellido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='clase',
            new_name='horarios',
        ),
    ]
