# Generated by Django 3.2.9 on 2021-11-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_api', '0004_alter_horario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
