# Generated by Django 3.2.9 on 2021-11-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_api', '0005_alter_plan_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='img',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
