# Generated by Django 3.2.8 on 2021-11-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_api', '0006_instructor_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aficion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=60, null=True)),
                ('correo', models.CharField(max_length=60)),
                ('aficiones', models.ManyToManyField(to='mandala_api.Aficion')),
            ],
        ),
    ]
