# Generated by Django 3.2.8 on 2021-11-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_api', '0007_aficion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
