# Generated by Django 3.2.8 on 2021-11-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandala_api', '0008_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='img',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
